name: Create Asana PR subtask
description: |
  Creates a PR subtask and assigns it to the team member in charge of the GitHub review.
  If the PR subtask already exists, it ensures the reviewer is assigned and the task is not marked 'completed'.
inputs:
  access-token:
    description: "Asana access token"
    required: true
    type: string
  asana-task-id:
    description: "Asana Task ID for the PR"
    required: string
    type: string
  github-reviewer-user:
    description: "GitHub username for the requested reviewer"
    required: true
    type: string
  github-token:
    description: "GitHub token"
    required: false
    type: string
runs:
  using: "composite"
  steps:
      - name: Get Asana user ID
        id: get-asana-user-id
        uses: duckduckgo/native-github-asana-sync@v1.9
        with:
          action: 'get-asana-user-id'
          github-username: ${{ inputs.github-reviewer-user }}
          github-pat: ${{ inputs.github-token }}

      - name: Get PR URL
        id: get-pr-url
        shell: bash
        run: |
          echo "url=https://github.com/${{ github.repository }}/pull/${{ github.event.number }}" >> "$GITHUB_OUTPUT"
        
      - name: "Create PR Subtask"
        shell: bash
        env:
          ASANA_ACCESS_TOKEN: ${{ inputs.access-token }}
        run: |
          # If the Asana User ID is not found, exit with an error
          if [[ -z "${{ steps.get-asana-user-id.outputs.asanaUserId }}" ]]; then
            echo "Error: Failed to get Asana user ID for GitHub user ${{ inputs.github-reviewer-user }}"
            exit 1
          else
            ${{ github.action_path }}/asana-create-pr-subtask.sh ${{ inputs.asana-task-id }} ${{ steps.get-asana-user-id.outputs.asanaUserId }} ${{ steps.get-pr-url.outputs.url }} ${{ github.event.repository.name }}
          fi
